# To read this file do:
# $ perldoc README

=head1 NAME

B<irstats2-filter-by-ip> - Filter module for Irstats2 to filter accesslog by ip/cidr or ip ranges or ip/netmask 

=head1 DESCRIPTION

This module is an extension for Irstats2 (see https://github.com/eprints/irstats2/) to filter accesslog if 
the ip logged is in a range configured in cfg/cfg.d/z_irstat2_filter_ipcidr_blocks.pl
This module should put offline the many GB of log table access of the software eprints.

To install:
 cp cfg/cfg.d/z_irstats2_filter_ipcidr_blocks.pl $EPRINTS_HOME/archives/<id>/cfg/cfg.d/z_irstat2_filter_ipcidr_blocks.pl
 cp cfg/plugins/EPrints/Plugin/Stats/Filter/IP.pm $EPRINTS_HOME/archives/<id>/cfg/plugins/EPrints/Plugin/Stats/Filter/IP.pm


Add in cfg/cfg.d/z_irstats2.pl 
   $c->{irstats2}->{datasets} = {access => { filters => [ 'Robots', 'Repeat','IP' ] } },

=head1 COPYRIGHT

    irstats2-filter-by-ip is Copyright (c) 2014 Enio Carboni - Italy
    This file is part of irstats2-filter-by-ip.

    irstats2-filter-by-ip is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    irstats2-filter-by-ip is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with offline.  If not, see <http://www.gnu.org/licenses/>.

=head1 SUPPORT / WARRANTY

The irstats2-filter-by-ip is free Open Source software. IT COMES WITHOUT WARRANTY OF ANY KIND.

